# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\annotation.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Annotation(object):
    def setupUi(self, Annotation):
        Annotation.setObjectName("Annotation")
        Annotation.resize(600, 350)
        Annotation.setStyleSheet("#title_frame {\n"
"    border-top-left-radius: 10px;  /* Rounds the top left corner of the title frame */\n"
"    background-color: #4789f3;  /* Sets a blue background color for the title frame, making it stand out */\n"
"}\n"
"\n"
"#main_frame {\n"
"    border-bottom-right-radius: 10px;  /* Rounds the bottom right corner of the main frame */\n"
"    border-bottom-left-radius: 10px;  /* Rounds the bottom left corner of the main frame */\n"
"    background-color: #d8d8d8;  /* Sets a light grey background color for the main frame */\n"
"}\n"
"\n"
"#title_frame QLabel {\n"
"    color: #fff;  /* Sets the text color to white for labels in the title frame for better readability */\n"
"    background-color: transparent;  /* Ensures the label background is transparent */\n"
"}\n"
"\n"
"#icon_label {\n"
"    min-width: 30px;  /* Sets a minimum width for the icon label */\n"
"    min-height: 30px;  /* Sets a minimum height for the icon label */\n"
"    max-width: 30px;  /* Sets a maximum width for the icon label to ensure it stays a fixed size */\n"
"    max-height: 30px;  /* Sets a maximum height for the icon label */\n"
"    border-radius: 15px;  /* Rounds the edges of the icon label to make it circular */\n"
"    border: 1px solid #fff;\n"
"}\n"
"\n"
"#title_frame QPushButton {\n"
"    border: none;  /* Removes the border from QPushButton in the title frame for a cleaner look */\n"
"    width: 50px;  /* Sets the width of the button */\n"
"    height: 40px;  /* Sets the height of the button */\n"
"}\n"
"\n"
"#maxmize_btn:hover, #minimize_btn:hover {\n"
"    background-color: #d8d8d8;  /* Changes the background color of maximize and minimize buttons on hover for visual feedback */\n"
"}\n"
"\n"
"#close_btn:hover {\n"
"    background-color: #c42b1c;  /* Changes the background color of the close button on hover to a distinct red, indicating a destructive action */\n"
"}\n"
"\n"
"#close_btn, #title_frame {\n"
"    border-top-right-radius: 10px;  /* Rounds the top right corner of the close button and the title frame for a softened edge */\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(Annotation)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.title_frame = QtWidgets.QFrame(self.centralwidget)
        self.title_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.title_frame.setStyleSheet("")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout_3.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.icon_label = QtWidgets.QLabel(self.title_frame)
        self.icon_label.setStyleSheet("#icon_label {   \n"
"                border-image: url(\"./static/icon/icon.png\")            \n"
"            }   ")
        self.icon_label.setText("")
        self.icon_label.setObjectName("icon_label")
        self.horizontalLayout_2.addWidget(self.icon_label)
        self.label_title = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_2.addWidget(self.label_title)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(952, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.minimize_btn = QtWidgets.QPushButton(self.title_frame)
        self.minimize_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/minimize.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon)
        self.minimize_btn.setIconSize(QtCore.QSize(20, 20))
        self.minimize_btn.setObjectName("minimize_btn")
        self.horizontalLayout.addWidget(self.minimize_btn)
        self.maxmize_btn = QtWidgets.QPushButton(self.title_frame)
        self.maxmize_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/full_window.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maxmize_btn.setIcon(icon1)
        self.maxmize_btn.setObjectName("maxmize_btn")
        self.horizontalLayout.addWidget(self.maxmize_btn)
        self.close_btn = QtWidgets.QPushButton(self.title_frame)
        self.close_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon2)
        self.close_btn.setIconSize(QtCore.QSize(20, 20))
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.title_frame, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("QWidget{\n"
"    background-color: #d1d1d1; \n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border: 1px solid rgb(80, 80, 80); /* Bordure subtile */\n"
"    border-top: none ; /* Bordure subtile */\n"
"}\n"
"QLineEdit {\n"
"    text-align: center;\n"
"    border: 1px solid #4d4d4d;\n"
"     background-color: #202020; \n"
"    color: #d1d1d1;\n"
"    border-radius: 5px;\n"
"    height: 50px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"\n"
"}\n"
"\n"
"QLabel {\n"
"    color: black; /* Texte en noir */\n"
"    font: bold 15px \"Arial\";\n"
"    line-height: 30;       /* Espacement entre les lignes de texte */\n"
"    letter-spacing: 1px;    /* Espacement entre les lettres */\n"
"    qproperty-alignment: AlignLeft;\n"
"    padding: 5;\n"
"\n"
"}\n"
"\n"
"QPushButton {\n"
"    text-align: left;\n"
"    border: 1px solid #4d4d4d;\n"
"     background-color: #202020; \n"
"    color: #d1d1d1;\n"
"    border-radius: 5px;\n"
"    height: 50px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #777;\n"
"}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_cin = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_cin.setStyleSheet("")
        self.lineEdit_cin.setObjectName("lineEdit_cin")
        self.gridLayout_2.addWidget(self.lineEdit_cin, 1, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_sortir = QtWidgets.QPushButton(self.widget)
        self.pushButton_sortir.setObjectName("pushButton_sortir")
        self.horizontalLayout_4.addWidget(self.pushButton_sortir)
        spacerItem1 = QtWidgets.QSpacerItem(378, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton_annoter = QtWidgets.QPushButton(self.widget)
        self.pushButton_annoter.setObjectName("pushButton_annoter")
        self.horizontalLayout_4.addWidget(self.pushButton_annoter)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(579, 137, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("QLabel\n"
"{\n"
"    border: none ; /* Bordure subtile */\n"
"}")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)
        Annotation.setCentralWidget(self.centralwidget)

        self.retranslateUi(Annotation)
        QtCore.QMetaObject.connectSlotsByName(Annotation)

    def retranslateUi(self, Annotation):
        _translate = QtCore.QCoreApplication.translate
        Annotation.setWindowTitle(_translate("Annotation", "MainWindow"))
        self.label_title.setText(_translate("Annotation", "Annotation"))
        self.pushButton_sortir.setText(_translate("Annotation", "Sortir"))
        self.pushButton_annoter.setText(_translate("Annotation", "Annoter"))
        self.label.setText(_translate("Annotation", "Entrez le numéro de CNE ou scannez le QR code de l\'élève"))
from static import resource_rc
