# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1227, 849)
        Form.setStyleSheet("/* Set style for app title widget */\n"
"#titleWidget {\n"
"    border-image: url(:/img/img/206954.jpg);\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"}\n"
"\n"
"#titleWidget QLabel {\n"
"    color: rgba(255, 255, 255, 0.8);\n"
"    font-family: \"Stencil\";\n"
"}\n"
"\n"
"#titleLabel1 {\n"
"    font-size: 40px;\n"
"}\n"
"\n"
"#titleLabel2 {\n"
"    font-size: 30px;\n"
"}\n"
"\n"
"/* Set style for function widget */\n"
"#funcWidget {\n"
"    background-color: #fff;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-top: 2px solid #343434;\n"
"    border-right: 2px solid #343434;\n"
"    border-bottom: 2px solid #343434;\n"
"}\n"
"\n"
"/* Set style for all the QLabel in function widget */\n"
"#funcWidget QLabel {\n"
"    color: #505050;\n"
"}\n"
"\n"
"/* Set style for login label and register label in function widget */\n"
"#loginLabel, #registerLabel {\n"
"    \n"
"    font-size: 30px;\n"
"}\n"
"\n"
"/* Set style for all the QLineEdit in function widget */\n"
"#funcWidget QLineEdit {\n"
"    border: 1px solid #e5ebf0;\n"
"    border-radius: 5px;\n"
"    padding: 5px 10px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"#funcWidget QLineEdit:focus {\n"
"    border-color: #5500ff;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(110, 835, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.titleWidget = QtWidgets.QWidget(Form)
        self.titleWidget.setMinimumSize(QtCore.QSize(550, 650))
        self.titleWidget.setMaximumSize(QtCore.QSize(550, 650))
        self.titleWidget.setObjectName("titleWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.titleWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 224, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel2 = QtWidgets.QLabel(self.titleWidget)
        self.titleLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel2.setObjectName("titleLabel2")
        self.verticalLayout.addWidget(self.titleLabel2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 224, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout.addWidget(self.titleWidget, 0, 1, 2, 1)
        self.funcWidget = QtWidgets.QStackedWidget(Form)
        self.funcWidget.setMinimumSize(QtCore.QSize(550, 650))
        self.funcWidget.setMaximumSize(QtCore.QSize(550, 650))
        self.funcWidget.setStyleSheet("")
        self.funcWidget.setObjectName("funcWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(30)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.loginLabel = QtWidgets.QLabel(self.page)
        self.loginLabel.setStyleSheet("#loginLabel {\n"
"    color: #000;\n"
"}")
        self.loginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginLabel.setObjectName("loginLabel")
        self.verticalLayout_5.addWidget(self.loginLabel)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_4.addWidget(self.lineEdit_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exitBtn = QtWidgets.QPushButton(self.page)
        self.exitBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.exitBtn.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    border: 1px solid #4d4d4d;\n"
"     background-color: #202020; \n"
"    color: #d1d1d1;\n"
"    border-radius: 5px;\n"
"    height: 40px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #777;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/logout-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn.setIcon(icon)
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout.addWidget(self.exitBtn)
        self.loginBtn = QtWidgets.QPushButton(self.page)
        self.loginBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.loginBtn.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    border: 1px solid #4d4d4d;\n"
"     background-color: #202020; \n"
"    color: #d1d1d1;\n"
"    border-radius: 5px;\n"
"    height: 40px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #777;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/login-64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginBtn.setIcon(icon1)
        self.loginBtn.setObjectName("loginBtn")
        self.horizontalLayout.addWidget(self.loginBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 1, 1, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(368, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.keyboard_btn = QtWidgets.QPushButton(self.page)
        self.keyboard_btn.setStyleSheet("QPushButton {\n"
"    text-align: left;\n"
"    border: 1px solid #4d4d4d;\n"
"     background-color: #202020; \n"
"    color: #d1d1d1;\n"
"    border-radius: 5px;\n"
"    height: 25px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"    padding-bottom: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #777;\n"
"}")
        self.keyboard_btn.setObjectName("keyboard_btn")
        self.horizontalLayout_4.addWidget(self.keyboard_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 2, 1, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 129, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem7, 0, 1, 1, 2)
        self.funcWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(30)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.registerLabel = QtWidgets.QLabel(self.page_2)
        self.registerLabel.setStyleSheet("#registerLabel {\n"
"    color: #000;\n"
"}")
        self.registerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.registerLabel.setObjectName("registerLabel")
        self.verticalLayout_6.addWidget(self.registerLabel)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_7.addWidget(self.lineEdit_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_8.addWidget(self.lineEdit_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backBtn = QtWidgets.QPushButton(self.page_2)
        self.backBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.backBtn.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/arrow-80-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backBtn.setIcon(icon2)
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout_2.addWidget(self.backBtn)
        self.createBtn = QtWidgets.QPushButton(self.page_2)
        self.createBtn.setMinimumSize(QtCore.QSize(0, 30))
        self.createBtn.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/check-mark-3-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createBtn.setIcon(icon3)
        self.createBtn.setObjectName("createBtn")
        self.horizontalLayout_2.addWidget(self.createBtn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 129, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem9, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 1, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 2, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem12 = QtWidgets.QSpacerItem(453, 56, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 3, 0, 1, 3)
        self.funcWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.funcWidget, 0, 2, 2, 1)
        spacerItem13 = QtWidgets.QSpacerItem(111, 835, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 0, 0, 2, 1)

        self.retranslateUi(Form)
        self.funcWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titleLabel2.setText(_translate("Form", "T3 Shield"))
        self.loginLabel.setText(_translate("Form", "Authentification"))
        self.label.setText(_translate("Form", "Nom d\'utilisateur"))
        self.label_2.setText(_translate("Form", "Mot de passe"))
        self.exitBtn.setText(_translate("Form", "Sortir"))
        self.loginBtn.setText(_translate("Form", "Se connecter"))
        self.keyboard_btn.setText(_translate("Form", "⌨"))
        self.registerLabel.setText(_translate("Form", "Register"))
        self.label_3.setText(_translate("Form", "Username"))
        self.label_4.setText(_translate("Form", "Password"))
        self.backBtn.setText(_translate("Form", "Back"))
        self.createBtn.setText(_translate("Form", "Create"))
from static import resource_rc
